language: ruby

rvm:
- 2.1
- 2.0.0
- ruby-head

matrix:
  allow_failures:
  - rvm: ruby-head

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5277d18c3b948d940bc9
    on_success: change
    on_failure: always
    on_start: false
